require '../lib/QueueGpaises.rb'

paises = QueueGe.new(5)
paises.push("Brasil")
paises.push("Argentina")
paises.push("Paraguai")
paises.push("Bolivia")
paises.push("Equador")
paises.push("Uruguai")
paises.pop()
paises.pop()
paises.push("Chile")
paises.pop()
paises.pop()
paises.print()